service: serverless-api

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  save_image:
    handler: functions/SaveImage/SaveImage.handler
    events:
      - http:
          path: api/save_image
          method: post
