service: serverless-api

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  authenticator:
    handler: functions/authenticator/authenticator.handler
    events:
      - http:
          path: api/authenticator
          method: get
